version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "acorn"
        versions: ["<latest"]
      - dependency-name: "@babel/traverse"
        versions: ["<latest"]
      - dependency-name: "ajv"
        versions: ["<latest"]
      - dependency-name: "semver"
        versions: ["<latest"]
      - dependency-name: "bcrypt"
        versions: ["<latest"]
      - dependency-name: "qs"
        versions: ["<latest"]
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "acorn"
        versions: ["<latest"]
      - dependency-name: "@babel/traverse"
        versions: ["<latest"]
      - dependency-name: "ajv"
        versions: ["<latest"]
      - dependency-name: "semver"
        versions: ["<latest"]
      - dependency-name: "bcrypt"
        versions: ["<latest"]
      - dependency-name: "qs"
        versions: ["<latest"]