version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    commit-message:
      prefix: "Bump"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "acorn"
        versions: ["6.0.0"]
      - dependency-name: "@babel/traverse"
        versions: ["7.0.0"]
      - dependency-name: "ajv"
        versions: ["6.0.0"]
      - dependency-name: "semver"
        versions: ["6.3.0"]
      - dependency-name: "bcrypt"
        versions: ["5.0.0"]
      - dependency-name: "qs"
        versions: ["6.9.0"]
    allow:
      - dependency-name: "mongoose"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "bson"
        versions: ["1.1.7"]
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    commit-message:
      prefix: "Bump"
    labels:
      - "dependencies"
    allow:
      - dependency-name: "postcss"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "react-scripts"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "qs"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
