version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "acorn"
        versions: ["<6.0.0"]
      - dependency-name: "@babel/traverse"
        versions: ["<7.0.0"]
      - dependency-name: "ajv"
        versions: ["<6.0.0"]
      - dependency-name: "semver"
        versions: ["<6.3.0"]
      - dependency-name: "bcrypt"
        versions: ["<5.0.0"]
      - dependency-name: "qs"
        versions: ["<6.9.0"]
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "acorn"
        versions: ["<6.0.0"]
      - dependency-name: "@babel/traverse"
        versions: ["<7.0.0"]
      - dependency-name: "ajv"
        versions: ["<6.0.0"]
      - dependency-name: "semver"
        versions: ["<6.3.0"]
      - dependency-name: "bcrypt"
        versions: ["<5.0.0"]
      - dependency-name: "qs"
        versions: ["<6.9.0"]
